-- MySQL Script generated by MySQL Workbench
-- 10/08/17 18:34:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoWebCasamento` DEFAULT CHARACTER SET utf8 ;
USE `projetoWebCasamento` ;

-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `disc_usuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Casamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Casamento` (
  `idCasamento` INT NOT NULL,
  `orcamentoTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idCasamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Convidado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Convidado` (
  `statusConvidado` VARCHAR(100) NOT NULL,
  `Casamento_idCasamento` INT NOT NULL,
  `idUsuarioProfissional` INT NOT NULL,
  INDEX `fk_Convidado_Casamento1_idx` (`Casamento_idCasamento` ASC),
  INDEX `fk_Convidado_Usuario1_idx` (`idUsuarioProfissional` ASC),
  PRIMARY KEY (`idUsuarioProfissional`),
  CONSTRAINT `fk_Convidado_Casamento1`
    FOREIGN KEY (`Casamento_idCasamento`)
    REFERENCES `projetoWebCasamento`.`Casamento` (`idCasamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Convidado_Usuario1`
    FOREIGN KEY (`idUsuarioProfissional`)
    REFERENCES `projetoWebCasamento`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Profissional` (
  `idUsuarioProfissional` INT NOT NULL,
  PRIMARY KEY (`idUsuarioProfissional`),
  INDEX `fk_Profissional_Usuario1_idx` (`idUsuarioProfissional` ASC),
  CONSTRAINT `fk_Profissional_Usuario1`
    FOREIGN KEY (`idUsuarioProfissional`)
    REFERENCES `projetoWebCasamento`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Conjuge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Conjuge` (
  `Casamento_idCasamento` INT NOT NULL,
  `idUsuarioProfissional` INT NOT NULL,
  PRIMARY KEY (`idUsuarioProfissional`),
  INDEX `fk_Conjuge_Casamento1_idx` (`Casamento_idCasamento` ASC),
  INDEX `fk_Conjuge_Usuario1_idx` (`idUsuarioProfissional` ASC),
  CONSTRAINT `fk_Conjuge_Casamento1`
    FOREIGN KEY (`Casamento_idCasamento`)
    REFERENCES `projetoWebCasamento`.`Casamento` (`idCasamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conjuge_Usuario1`
    FOREIGN KEY (`idUsuarioProfissional`)
    REFERENCES `projetoWebCasamento`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `preco` FLOAT NOT NULL,
  `statusDisponibilizado` VARCHAR(100) NOT NULL,
  `Profissional_idUsuarioProfissional` INT NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_Servico_Profissional1_idx` (`Profissional_idUsuarioProfissional` ASC),
  CONSTRAINT `fk_Servico_Profissional1`
    FOREIGN KEY (`Profissional_idUsuarioProfissional`)
    REFERENCES `projetoWebCasamento`.`Profissional` (`idUsuarioProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Tarefa` (
  `idTarefa` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `data` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Servico_idServico` INT NOT NULL,
  `Casamento_idCasamento` INT NOT NULL,
  PRIMARY KEY (`idTarefa`),
  INDEX `fk_Tarefa_Servico1_idx` (`Servico_idServico` ASC),
  INDEX `fk_Tarefa_Casamento1_idx` (`Casamento_idCasamento` ASC),
  CONSTRAINT `fk_Tarefa_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `projetoWebCasamento`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tarefa_Casamento1`
    FOREIGN KEY (`Casamento_idCasamento`)
    REFERENCES `projetoWebCasamento`.`Casamento` (`idCasamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Convite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Convite` (
  `idConvite` INT NOT NULL,
  `destinatarios` VARCHAR(1000) NOT NULL,
  `mensagem` VARCHAR(500) NOT NULL,
  `Casamento_idCasamento` INT NOT NULL,
  PRIMARY KEY (`idConvite`),
  INDEX `fk_Convite_Casamento1_idx` (`Casamento_idCasamento` ASC),
  CONSTRAINT `fk_Convite_Casamento1`
    FOREIGN KEY (`Casamento_idCasamento`)
    REFERENCES `projetoWebCasamento`.`Casamento` (`idCasamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoWebCasamento`.`Profissional_has_Casamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoWebCasamento`.`Profissional_has_Casamento` (
  `Profissional_idUsuarioProfissional` INT NOT NULL,
  `Casamento_idCasamento` INT NOT NULL,
  PRIMARY KEY (`Profissional_idUsuarioProfissional`, `Casamento_idCasamento`),
  INDEX `fk_Profissional_has_Casamento_Casamento1_idx` (`Casamento_idCasamento` ASC),
  INDEX `fk_Profissional_has_Casamento_Profissional1_idx` (`Profissional_idUsuarioProfissional` ASC),
  CONSTRAINT `fk_Profissional_has_Casamento_Profissional1`
    FOREIGN KEY (`Profissional_idUsuarioProfissional`)
    REFERENCES `projetoWebCasamento`.`Profissional` (`idUsuarioProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profissional_has_Casamento_Casamento1`
    FOREIGN KEY (`Casamento_idCasamento`)
    REFERENCES `projetoWebCasamento`.`Casamento` (`idCasamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
